# Generated by Django 3.1.5 on 2021-01-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcticle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='id_news',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(verbose_name='Содержимое статьи'),
        ),
    ]
